= ICD Proof of Concept

== Intro
The idea with this proof of concept is to be able to keep the documentation with the code.
the directory-maven-plugin and maven-resources-plugin are used to assemgle the ICD adocs into a common folder.
Jbake then uses a template to assmble the pieces of the ICD docs into the completed ICD.

The benifit to this method is that when a new ICD element is added, the developer simply has to use the template and the documentation wil automatically get updated.

== Build Instructions

Run `mvn clean install` from the asciidoctor-maven-multimodule directory.

The ICD document will be in documentation/target/docs/pdf.

== How it Works
In the developers project, they include an adoc that starts with icd-, example: `icd-ha-interface.adoc`.
The maven-resources-plugin from the root pom filter copies that adoc to the common folder in the parent pom's target directory during a build.

When the documents module gets built, it copies over its document resources then runs Jbake on the target directory, saving hte results in the documents modules target directory.
After Jbake, the asciidoctor plugin uses the baked .adocs to make the ICD PDF file.
